from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('ledblink', src, depend = ['LEDBLINK_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
