from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('ledblink', src, depend = ['PKG_USING_LEDBLINK'], CPPPATH = CPPPATH)

Return('group')
